Add controllers
PetrVladimirovich/java-shareit pull request #2
Opened 2023-02-14 17:39 UTC by PetrVladimirovich

2023-02-15 19:07 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохая работа, давай поправим то что отметил и еще пару моментов:

1.  **Учесть и поправить нейминг методов:** get - это или получение объекта или исключение, find - это или объект или null
2. Давай все логи будем переносить на англ язык, уже пора.
3. Мое сугубо личное мнение: понимаю что вас возможно учили называть Dao
4. Улучшить исключения 

Буду ждать правки =)

2023-02-15 19:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/dao/BookingDao.java
> +public interface BookingDao {
**Учесть правила нейнинга**

2023-02-15 19:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/dao/ItemDao.java
> +public interface ItemDao {
**Учесть правила нейнинга**

2023-02-15 19:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotBlank
Для такого рода аннотаций можно добавить еще message внутри скобок

2023-02-15 19:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +public interface ItemService {
Учесть правила нейминга

2023-02-15 19:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        log.debug("ItemService: выполнено findAllItems.");
Давай все логи будем переносить на англ язык, уже пора.

2023-02-15 19:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public UserDto updateUser(@PathVariable Long userId, @Validated(Update.class) @RequestBody UserDto userDto) {
@Validated(Update.class) - просто попробовать решил, или несет практическую пользу такое ограничение интерфейсом?

2023-02-15 19:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<ItemDto> findAllItems(@RequestHeader("X-Sharer-User-Id") Long userId) {
"X-Sharer-User-Id" эта штука много где повторяется рекомендую ее вынести в класс Constants и использовать переменную

2023-02-15 19:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                () -> new NotFoundException(Item.class.toString(), itemId)
Давай создадим специальное исключение ItemFoundException наследника NotFoundException и сделаем так чтобы каждый раз не повторять текст:
`() -> new ItemFoundException(userId));`

*p.s для остальных исключений тоже можно подумать в эту сторону ...*

2023-02-15 20:04 UTC, PetrVladimirovich commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public UserDto updateUser(@PathVariable Long userId, @Validated(Update.class) @RequestBody UserDto userDto) {
несет, у меня postman 20 тестов не пускал с пользователями(

2023-02-16 18:28 UTC, PetrVladimirovich commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +public interface ItemService {
?

2023-02-17 04:37 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-02-17 11:58 UTC, merged