feat: Добавить Репозитории и логику
PetrVladimirovich/java-shareit pull request #3
Opened 2023-03-07 13:44 UTC by PetrVladimirovich

2023-03-08 06:25 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом отличная работа, давай чутка может ее улучшим и будет зачет:

1) То что отметил
2) @JsonFormat не заметил что используем
3) Улучшить логгирование, а то его маловато...

2023-03-08 06:25 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "status_string")
status_string - не лучшее название, можно просто status

2023-03-08 18:24 UTC, PetrVladimirovich commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "status_string")
Не особо понял зачем @JsonFormat, если у нас автоматом Jackson подключается?

2023-03-09 06:41 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "status_string")
Ну вам вроде рассказывают про него и некоторые студенты используют, в целом это просто позволяет контролировать формат даты везде чтобы не было рассинхронов , в целом конечно нужно использовать по необходимости

2023-03-09 06:42 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-03-12 06:26 UTC, merged