feat: Добавить Тесты и доп функционал
PetrVladimirovich/java-shareit pull request #4
Opened 2023-03-18 07:06 UTC by PetrVladimirovich

2023-03-19 09:34 UTC, krylov-sergey-sergeevich requested changes
Привет, все хорошо, давай по мелочам улучшим и будет зачет =)

1) Рекомендую from, size объеденить в один объект и по сервисам в методах его принимать, так будет короче и лаконичнее, если вдруг там потом появится например параметр filter то не придется во всех методах его дописывать.
2) new ResponseEntity<>(что-то, HttpStatus.OK); - это не обязательно так писать можно ограничиться и "что-то"- мне кажется тесты должны пройти и с таким ответом
3) Давай создадим класс DateUtils и будем создавать объекты времени через него, это позволит унифицировать способ получения времени и если будут правки делать их в 1 месте.

DateUtils.now() вместо LocalDateTime.now()

офтоп: а разве inmemory реализацию уже нельзя удалять?

2023-03-19 09:34 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<artifactId>commons-lang3</artifactId>
Для чего используем эту библиотеку?

2023-03-19 09:34 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +@ControllerAdvice(assignableTypes = {ItemController.class, UserController.class, BookingController.class,
Лучше не перечислять контроллеры, а по дефолту для всех пусть работает, чтобы не забыть потом случайно новые включить.

2023-03-19 09:34 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemRepository.java
> +        return null;
так и должно быть?

2023-03-19 09:34 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepositoryImpl.java
> +    private EntityManager entityManager;
final

2023-03-19 09:34 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SS")
"yyyy-MM-dd'T'HH:mm:ss.SS" - помоему этот формат оч много где встречается, мжт вынесем в константы?

2023-03-19 09:34 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    private String text;
давай добавим пустую строку после чтобы разделить визуально

2023-03-19 09:34 UTC, krylov-sergey-sergeevich commented on src/main/resources/application.properties
> +spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
Разница есть в нашем случае?

2023-03-19 12:32 UTC, PetrVladimirovich commented on pom.xml
> +			<artifactId>commons-lang3</artifactId>
Для StringUtils

2023-03-19 12:35 UTC, PetrVladimirovich commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemRepository.java
> +        return null;
=)

2023-03-19 12:38 UTC, PetrVladimirovich commented on src/main/resources/application.properties
> +spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
нет по разному пробовал тесты не проходили, обратно забыл вернуть)

2023-03-19 13:35 UTC, PetrVladimirovich commented on pom.xml
> +			<artifactId>commons-lang3</artifactId>
1. Не понял, создать еще класс с этими полями и везде менять на него? а смысл? потом же также везде дописывать надо и в Логах и в тестах(
2. Без HttpStatus.OK не хочет((
3. Тоже не понял, создать класс и внутри его метода now() вызывать LocalDateTime.now()? =)

2023-03-20 06:18 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<artifactId>commons-lang3</artifactId>
1) Да, рекомендую так. Что дописывать? У нас по сути вся информация о странице которую мы захотим получить будет в одном объекте, не будем захломлять методы 2-3 параметрами, а вместо них будет один
2) Хорошо
3) Да именно, это для того что если вдруг мы захотим поменять логику делать это в одном месте и mock для тестов легче делать

2023-03-20 06:25 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки, вижу что пункт 1 и 3 не сделаны они не критичны, поэтому зачет!

офтоп: но я бы рекомендовал бы подумать о пунктах 1 и 3 если будет время то реализовать

2023-03-20 08:24 UTC, PetrVladimirovich commented on pom.xml
> +			<artifactId>commons-lang3</artifactId>
Окей постараюсь сделать!

2023-03-20 08:24 UTC, merged