feat: Добавить docker
PetrVladimirovich/java-shareit pull request #5
Opened 2023-03-30 18:53 UTC by PetrVladimirovich

2023-03-31 21:24 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохая работа

- Почему логи на русский были перенесены?
- Отметил пару мест на основе которых рекомендую и в других местах аналогично поправить - это касается констант

Буду ждать с комментариями и правками =)

2023-03-31 21:24 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    private static final String API_PREFIX = "/bookings";
Можно вынести в класс констант как вариант, не обязательно

2023-03-31 21:24 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public static final String BOOKER_ID_TAG = "X-Sharer-User-Id";
Просится в класс констант

2023-03-31 21:24 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        BookingState state = BookingState.from(stateParam)
Я бы оформил это в какой то validation метод

2023-03-31 21:24 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        BookingState state = BookingState.from(stateParam)
и тут переиспользовать метод валидации

2023-03-31 21:24 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/commonclasses/ErrorHandler.java
> +@ControllerAdvice(assignableTypes = {BookingController.class, ItemRequestController.class, ItemController.class})
Не рекомендую тут перечислять, это опасно, лучше оставить по дефолту чтобы для всех работало - или есть причины?

2023-03-31 21:24 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/item/ItemClient.java
> +    private static final String API_PREFIX = "/items";
Я бы в класс констант бы вывел

2023-03-31 21:24 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SS")
"yyyy-MM-dd'T'HH:mm:ss.SS" - много где повторяется мжт в константы?

2023-03-31 21:24 UTC, krylov-sergey-sergeevich commented on server/src/test/java/ru/practicum/shareit/ShareItTests.java
> +class ShareItTests {
?)

2023-03-31 21:24 UTC, krylov-sergey-sergeevich commented on server/src/test/java/ru/practicum/shareit/booking/BookingServiceIT.java
> +    @Sql("classpath:add_users.sql")
Подход неплохой, но надо понимать плюсы и минусы

2023-04-01 02:16 UTC, PetrVladimirovich commented on gateway/src/main/java/ru/practicum/shareit/commonclasses/ErrorHandler.java
> +@ControllerAdvice(assignableTypes = {BookingController.class, ItemRequestController.class, ItemController.class})
а почему опасно?

2023-04-01 17:38 UTC, PetrVladimirovich commented on gateway/src/main/java/ru/practicum/shareit/item/ItemClient.java
> +    private static final String API_PREFIX = "/items";
Блин, все время про это забываю

2023-04-01 17:39 UTC, PetrVladimirovich commented on server/src/test/java/ru/practicum/shareit/ShareItTests.java
> +class ShareItTests {
?))

2023-04-01 17:40 UTC, PetrVladimirovich commented on server/src/test/java/ru/practicum/shareit/booking/BookingServiceIT.java
> +    @Sql("classpath:add_users.sql")
а каковы минусы?

2023-04-01 17:48 UTC, PetrVladimirovich commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        BookingState state = BookingState.from(stateParam)
Не много не догоняю о чем? Он же или имеешь в виду в util класс вынести метод BookingState.from(stateParam)?

2023-04-01 19:48 UTC, PetrVladimirovich commented on gateway/src/main/java/ru/practicum/shareit/commonclasses/ErrorHandler.java
> +@ControllerAdvice(assignableTypes = {BookingController.class, ItemRequestController.class, ItemController.class})
Вообщем на GitHub 12 тестов не проходит без (assignableTypes = {BookingController.class, ItemRequestController.class, ItemController.class})

2023-04-02 06:52 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/commonclasses/ErrorHandler.java
> +@ControllerAdvice(assignableTypes = {BookingController.class, ItemRequestController.class, ItemController.class})
Интересно..... Опасно тем что после того как добавится новый контроллер забудешь его сюда добавить и в итоге исключения не будут обрабатываться должным образом

2023-04-02 06:56 UTC, krylov-sergey-sergeevich commented on server/src/test/java/ru/practicum/shareit/booking/BookingServiceIT.java
> +    @Sql("classpath:add_users.sql")
Минусы не критичные, но их надо знать:

- Сложность: Вместе с увеличением числа тестовых методов и скриптов, управление всеми этими SQL-скриптами может стать сложным. Это может затруднить поддержку и обновление тестов.

- Неэффективность: Запуск SQL-скриптов перед каждым тестом может замедлить процесс тестирования, особенно при работе с большими объемами данных.

- Непортируемость: Использование SQL-скриптов может привести к проблемам с портируемостью, если ваше приложение должно работать с разными типами баз данных. Вам, возможно, придется поддерживать несколько версий скриптов для разных баз данных.

- Более сложный код: Использование аннотации @Sql может делать код тестов более сложным и трудным для понимания, особенно если у вас есть много скриптов и условий для их выполнения.

2023-04-02 06:57 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-04-02 07:10 UTC, merged